### ISSUE TITLE
UX bux: Cell type dropdown width

### ISSUE THREAD

**Issue by jeffpaul** [10up/mce-table-buttons#9]
**Describe the bug**
In testing #8, David Chabbi came across the following:
> UX visual issue. Cell type dropdown needs width increased. Screenshot attached.

![Screenshot 2021-02-03 at 11 54 12](https://user-images.githubusercontent.com/2818133/108416645-9c1c6e80-71f4-11eb-97bf-483ed27d8317.png)

**Steps to Reproduce**

**Expected behavior**
Cell type dropdown items should be fully visible within the dropdown.

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by dinhtungdu** [comment]
@jeffpaul This is a bug in the TinyMCE table plugin, not our plugin. Although we can override it with custom CSS,  I think we should mark this issue as `wontfix` because of the potential conflict.

**Comment by jeffpaul** [comment]
@dinhtungdu it looks like we're using TinyMCE plugin 4.7.11, might it be worth looking into a bump of that to something more current to potentially resolve this issue?

**Comment by dinhtungdu** [comment]
@jeffpaul I tried upgrading the table plugin to 4.9.1 and the issue still occurs. The latest version of the table plugin is 5.8.1 but it doesn't compatible with WP TinyMCE.
